version: '2'
services:
    mimic_server:
        image: mimic
        ports:
            - "8901:8901"
    bootstrap:
        image: mimic
        command: python /mimic/bin/mimic-collect-anonymous.py --endpoint http://mimic_server:8901
        depends_on: 
         - mimic_server

